"""Akatsuki core facade module providing backward-compatible exports.

This module unifies all functional subsystems (storage, index, vectors,
search, graph, verify, mutations, MCP, and CLI) for backward compatibility
while maintaining clean modular internal architecture.
"""

from akatsuki.cli import (
    cli_append,
    cli_blast,
    cli_contract,
    cli_daily,
    cli_get,
    cli_init,
    cli_lint,
    cli_list,
    cli_log,
    cli_map,
    cli_projects,
    cli_query,
    cli_read,
    cli_reconcile,
    cli_replace,
    cli_search,
    cli_services,
    cli_set,
    cli_test,
    cli_verify,
    cli_write,
    main,
)
from akatsuki.cli.parser import build_parser
from akatsuki.constants import (
    DEFAULT_EMBED_BATCH_SIZE,
    DEFAULT_EMBED_MODEL,
    DOMAIN_DIRS,
    DOMAIN_MOCS,
    HAVE_FCNTL,
    HAVE_PYYAML,
    RAW_EXTS,
    VERSION,
)
from akatsuki.graph import calculate_blast_radius, traverse_graph
from akatsuki.index import execute_sql_query, fts_db_context, get_fts_db, sync_fts_index
from akatsuki.markdown import (
    apply_token_budget,
    extract_headings,
    normalize_heading,
    replace_markdown_section,
    slice_markdown_section,
)
from akatsuki.mcp import (
    MCP_RESOURCES,
    MCP_TOOLS,
    dispatch_single_request,
    handle_mcp_call,
    handle_mcp_resource_read,
    run_mcp_server,
)
from akatsuki.mutations import (
    append_section_to_note,
    append_work_log,
    list_notes_in_vault,
    replace_section_in_note,
    set_note_property,
    write_note,
)
from akatsuki.search import (
    build_fts_clause,
    expand_query_term,
    extract_note_contract,
    get_keypath,
    search_vault,
)
from akatsuki.storage import (
    CURRENT_VAULT_OVERRIDE,
    VaultLock,
    VaultNotFoundError,
    _yaml_format_scalar,
    auto_heal_frontmatter,
    contained_path,
    dump_frontmatter,
    ensure_daily_note,
    get_machine_id,
    get_vault,
    is_raw_path,
    parse_frontmatter,
    resolve_note_file,
    resolve_vault_path,
    validate_frontmatter_yaml,
    validate_note_content,
)
from akatsuki.vectors import (
    chunk_akatsuki_note,
    dot_product,
    encode_query,
    encode_texts,
    get_embed_model,
    get_external_embed_python,
    get_vectors_db,
    normalize_vector,
    pack_vector,
    search_vectors_akatsuki,
    sync_vectors_index,
    unpack_vector,
)
from akatsuki.verify import lint_vault, reconcile_vault, run_verification_tests, verify_links

__all__ = [
    "CURRENT_VAULT_OVERRIDE",
    "DEFAULT_EMBED_BATCH_SIZE",
    "DEFAULT_EMBED_MODEL",
    "DOMAIN_DIRS",
    "DOMAIN_MOCS",
    "HAVE_FCNTL",
    "HAVE_PYYAML",
    "MCP_RESOURCES",
    "MCP_TOOLS",
    "RAW_EXTS",
    "VERSION",
    "VaultLock",
    "VaultNotFoundError",
    "_yaml_format_scalar",
    "append_section_to_note",
    "append_work_log",
    "apply_token_budget",
    "auto_heal_frontmatter",
    "build_fts_clause",
    "build_parser",
    "calculate_blast_radius",
    "chunk_akatsuki_note",
    "cli_append",
    "cli_blast",
    "cli_contract",
    "cli_daily",
    "cli_get",
    "cli_init",
    "cli_lint",
    "cli_list",
    "cli_log",
    "cli_map",
    "cli_projects",
    "cli_query",
    "cli_read",
    "cli_reconcile",
    "cli_replace",
    "cli_search",
    "cli_services",
    "cli_set",
    "cli_test",
    "cli_verify",
    "cli_write",
    "contained_path",
    "dispatch_single_request",
    "dot_product",
    "dump_frontmatter",
    "encode_query",
    "encode_texts",
    "ensure_daily_note",
    "execute_sql_query",
    "expand_query_term",
    "extract_headings",
    "extract_note_contract",
    "fts_db_context",
    "get_embed_model",
    "get_external_embed_python",
    "get_fts_db",
    "get_keypath",
    "get_machine_id",
    "get_vault",
    "get_vectors_db",
    "handle_mcp_call",
    "handle_mcp_resource_read",
    "is_raw_path",
    "lint_vault",
    "list_notes_in_vault",
    "main",
    "normalize_heading",
    "normalize_vector",
    "pack_vector",
    "parse_frontmatter",
    "reconcile_vault",
    "replace_markdown_section",
    "replace_section_in_note",
    "resolve_note_file",
    "resolve_vault_path",
    "run_mcp_server",
    "run_verification_tests",
    "search_vault",
    "search_vectors_akatsuki",
    "set_note_property",
    "slice_markdown_section",
    "sync_fts_index",
    "sync_vectors_index",
    "traverse_graph",
    "unpack_vector",
    "validate_frontmatter_yaml",
    "validate_note_content",
    "verify_links",
    "write_note",
]

if __name__ == "__main__":
    main()
